version: '3.8'
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: d11b99db7f32c87194b9755d61be231d
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
